# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        AppBundle\Entity\SystemAccount:
            algorithm: bcrypt

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        db_provider:
            entity:
                class: AppBundle:SystemAccount
                property: email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
                
        main:
            pattern:    ^/
            #http_basic: ~
            provider: db_provider
            
            form_login:
                provider: db_provider
                login_path: /login
                check_path: /login_check
                use_forward: true
#            logout: true
            anonymous: true
            #anonymous: ~
#        #secured_area:
            logout:
                path: /logout
                target: /
#                
    access_control:
            - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: /register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/, roles: ROLE_USER }
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
