AppBundle\Entity\Invoices:
    type: entity
    table: invoices
    indexes:
        user_id:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        invoiceNumber:
            type: string
            nullable: false
            length: 150
            options:
                fixed: false
            column: invoice_number
        dateOfInvoice:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: date_of_invoice
        sellDate:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: sell_date
        maturityDate:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: maturity_date
        additionalInfo:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
            column: additional_info
        sellerVatNumber:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
            column: seller_vat_number
        sellerName:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: seller_name
        sellerAddress:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: seller_address
        buyerVatNumber:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
            column: buyer_vat_number
        buyerName:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: buyer_name
        buyerAddress:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: buyer_address
        totalPrice:
            type: decimal
            nullable: true
            precision: 12
            scale: 2
            column: total_price
    manyToOne:
        user:
            targetEntity: Users
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
